apiVersion: v1
defaultRules:
  rules:
    etcd: false
    kubeScheduler: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: devops
  service:
    type: LoadBalancer   # Expose Prometheus as a LoadBalancer
    port: 9090           # Port that Prometheus listens on
commonLabels:
  prometheus: devops
grafana:
  adminPassword: test123
  service:
    type: LoadBalancer   # Expose Grafana as a LoadBalancer
    port: 80             # Port that Grafana listens on