apiVersion: v1
kind: Service
metadata:
  name: kibana-loadbalancer
  namespace: default  # Altere para o namespace onde o Kibana está instalado
spec:
  selector:
    kibana.k8s.elastic.co/name: quickstart
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: LoadBalancer