settings:
  clusterName: eks-demo
  clusterEndpoint: 
serviceAccount:
  name: "karpenter-controller-eks-demo"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::471112841349:role/karpenter-controller-eks-demo"
controller:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi