apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: sock-shop-provisioner
spec:
  labels:
    karpenter.sh/provisioner-name: sock-shop-provisioner
    app: frontend
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [nano, micro, small, medium, large]
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
  providerRef:
    name: default