name: "Terraform / EKS / Deploy"

on:
  workflow_run:
    workflows: ["TFLint Checks"]
    types:
      - completed

permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: sa-east-1
          role-session-name: github-oidc-terraform-state

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      - name: Export Environment Variables
        id: export-env
        run: |
          cluster_endpoint=$(terraform output -raw cluster_endpoint)
          echo "CLUSTER_ENDPOINT=${cluster_endpoint}" >> $GITHUB_ENV
          echo ${{ env.CLUSTER_ENDPOINT }}
      
      - name: echo
        run: echo ${{ env.CLUSTER_ENDPOINT }}


      - name: Setup Kubeconfig
        run: aws eks --region sa-east-1 update-kubeconfig --name eks-demo

      - name: Setup Helm
        uses: actions/checkout@v3
      
      - name: Kubectl get nodes
        run: kubectl get nodes

      - name: Install Karpenter
        run: | 
           helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version 0.37.0 --namespace karpenter --create-namespace \
           --set settings.clusterEndpoint=${{ env.CLUSTER_ENDPOINT }} \
           -f karpenter/karpenter-values.yaml

      - name: Wait
        run: sleep 30

      - name: Apply Karpenter Node Pool
        run: | 
           kubectl apply -f karpenter/nodepool.yaml
